### PR TITLE
Update consumers.md

### PR DESCRIPTION
**Pull request by EricMadariaga**
RSSBus Driver technologies have moved to CData - http://www.cdata.com/news/q115/

### CODE REVIEW

**Comment by dingeins** [comment]
@EricMadariaga 

Thank you for your contribution. The Ecosystem page of OData.org is updated according to your two pull requests. "CData" is added to every item title. Please have a look at www.odata.org/ecosystem before we merge the pull requests.

In addition, would you like to write blog posts on OData.org about the CData Cloud Drivers and Connectors? Simply fill in the form at the left side of this page: http://www.odata.org/post-blogs-on-odata-org/ and we will create a contributor account for you if you are interested.

**Comment by EricMadariaga** [comment]
That is fine, though I think that people are more interested in the technology (ODBC Driver) than the company name.  Perhaps we could / should put the company name in the text description instead?  I just wouldn’t want people to think that it is some kind of special ‘cdata’ interface on ado.net, odbc, jdbc, etc – these are standard drivers that can be used from any client technology that supports them.  

 

Not a big deal really, but thought it might help.

 

I will definitely write something for the blog.  Expect something by early next week.  Thanks!

 

-Eric

**Comment by yidingcn** [comment]
@EricMadariaga 

It makes sense. I'll update the site page accordingly.

**Comment by dingeins** [comment]
@EricMadariaga

It makes sense. I'll update the site page accordingly.

**Comment by EricMadariaga** [comment]
Hi Yi, 

 

We have a great new blog post for the OData site (Connecting from salesforce to external OData sources).  I went to create a contributor account for the odata.org site and it appears that the link below is no longer working?  Is there an updated link where we can submit this post?

 

Thanks!

 

-Eric

**Comment by dingeins** [comment]
@EricMadariaga Thanks for reaching out. The OData.org infrastructure is now changed and blog post contribution shall be made by sending Pull Requests to this repo: https://github.com/ODataOrg/odataorg.github.io. The README file of the repo will guide you through the process of contributing a post. If any question when working on the post contribution, please let me know.

**Comment by EricMadariaga** [comment]
Great, thanks!

 

-Eric

**Pull request merged**
